---
problem: rankine-hugoniot
gamma: 1.4
kappa: 1.0
mean_molecular_weight: 1.0
t0: 0.0
tf: 1.0
max_steps: 2
cfl: 0.3
max_dt: 1.0
log_frequency: 1
output_frequency: 2
levels: [5, 5, 5]
lowest_level: 5
coords:
  - [0.0, 0.0, 0.0]
  - [1.0, 1.0, 1.0]
boundaries:
  xlow: reflecting
  xhigh: reflecting
  ylow: flow
  yhigh: flow
  zlow: flow
  zhigh: flow
catalyst:
  script: /path
  implementation: paraview
  implementation_directory: /path
