config = {
    "problem": "heating_and_cooling",
    "problem_parameters": {
        "fluid_mass_density": 1.0e-11,
        "fluid_temperature": 1000,
        "radiation_temperature": 3000,
    },
    "kappa": 1.0,
    "gamma": 1.4,
    "mean_molecular_weight": 1.0,
    "eos": "ideal",
    "limiter_id": 3,
    "closure_id": 2,
    "t0": 0.0,
    "tf": 40,
    "max_steps": 200,
    "cfl": 0.3,
    "max_dt": 1.0,
    "log_frequency": 1,
    "output_frequency": 1,
    "levels": [2, 2, 2],
    "coords": [
        [0.0, 0.0, 0.0],
        [1e7, 1.0, 1.0],
    ],
    "boundaries": {
        "xlow": "periodic",
        "xhigh": "periodic",
        "ylow": "periodic",
        "yhigh": "periodic",
        "zlow": "periodic",
        "zhigh": "periodic",
    },
    "output_method": "csv",
    "lowest_level": 2,
    "linear_solver": {
        "maxiter": 100,
        "rtol": 1.0e-7,
        "use_zero_guess": True,
    },
}
