---
problem: kh-instability

problem_parameters:
  pressure: 2.5
  background_density: 1.0
  background_velocity: -0.5
  strip_density: 2.0
  strip_velocity: 0.5
  perturbation_mode: 2
  perturbation_amplitude: 0.05
  perturbation_width: 0.035355339059327376  # 0.05 / sqrt(2)

gamma: 1.6667
kappa: 0.0
mean_molecular_weight: 1.0

t0: 0.0
tf: 2.5
max_steps: 10000
cfl: 0.3
max_dt: 5.0e-2

log_frequency: 1
output_frequency: 1

levels: [2, 2]
lowest_level: 2
coords:
  - [0.0, 0.0]
  - [1.0, 1.0]
boundaries:
  xlow: periodic
  xhigh: periodic
  ylow: periodic
  yhigh: periodic
catalyst:
  script: /path
  implementation: paraview
  implementation_directory: /path
