---
problem: kh-test
gamma: 1.6667
kappa: 0.0
mean_molecular_weight: 1.0
t0: 0.0
tf: 1.0
max_steps: 10000
cfl: 0.3
max_dt: 5.0e-2
log_frequency: 1
output_frequency: 100
levels: [8, 8, 4]
lowest_level: 8
coords:
  - [0.0, 0.0, 0.0]
  - [1.0, 1.0, 1.0]
boundaries:
  xlow: periodic
  xhigh: periodic
  ylow: periodic
  yhigh: periodic
  zlow: flow
  zhigh: flow
catalyst:
  script: /path
  implementation: paraview
  implementation_directory: /path
