---
problem: rayleigh_taylor

gamma: 1.4
mean_molecular_weight: 100000

# with radiation..
problem_parameters:
  boundary_z: 0.5e6
  density_upper: 2.0e-8
  density_lower: 1.0e-8
  p0: 0.0825  # 100 Kelvin
  velocity_amplitude: 1000.0
  radiation_energy_density: 1.0e-50
  pertub_width: 0.5e5
  wavelength: 1.0e6
kappa: 1.0e-7

t0: 0.0
tf: 10000.0
max_steps: 100
cfl: 0.2
max_dt: 1.0

log_frequency: 10
output_frequency: 10

levels: [6, 1, 6]
lowest_level: 6
coords:
  - [0.0, 0.0, 0.0]
  - [1e6, 1e6, 1e6]

boundaries:
  xlow: periodic
  xhigh: periodic
  ylow: periodic
  yhigh: periodic
  zlow: reflecting
  zhigh: reflecting
catalyst:
  script: ../tools/gridwriter.py
  implementation: paraview
  implementation_directory: /vast/home/yoonsoo/spack/var/spack/environments/flastro_paraview/.spack-env/view/lib64/catalyst/
