---
problem: sine-wave
gamma: 1.4
kappa: 1.0
mean_molecular_weight: 1.0
t0: 0.0
tf: 1.0
max_steps: 2
cfl: 0.3
max_dt: 1.0
log_frequency: 1
output_frequency: 10
levels: [3, 3, 3]
lowest_level: 1
coords:
  - [0.0, 0.0, 0.0]
  - [2.0, 1.0, 1.0]
boundaries:
  xlow: periodic
  xhigh: periodic
  ylow: flow
  yhigh: flow
  zlow: flow
  zhigh: flow
catalyst:
  script: /path
  implementation: paraview
  implementation_directory: /path
