---
problem: sine-wave
gamma: 1.4
kappa: 1.0e-100
mean_molecular_weight: 1.0

t0: 0.0
tf: 10000.0
max_steps: 1600
cfl: 0.3
max_dt: 1.0
log_frequency: 1
output_frequency: 100
levels: [9, 1, 1]
lowest_level: 9
coords:
  - [0.0, 0.0, 0.0]
  - [2.0, 1.0, 1.0]
boundaries:
  xlow: periodic
  xhigh: periodic
  ylow: flow
  yhigh: flow
  zlow: flow
  zhigh: flow
catalyst:
  script: /path
  implementation: paraview
  implementation_directory: /path
