---
problem: sod
gamma: 1.4
eos: ideal
spiner_file: titanium.sp5
spiner_matid: 2961
kappa: 1.0e-100
mean_molecular_weight: 1.0
t0: 0.0
tf: 1.0
max_steps: 5000
cfl: 0.3
max_dt: 1.0
log_frequency: 1000
output_frequency: 1000
levels: [10, 5, 5]
lowest_level: 10
coords:
  - [0.0, 0.0, 0.0]
  - [1.0, 1.0, 1.0]
boundaries:
  xlow: reflecting
  xhigh: reflecting
  ylow: flow
  yhigh: flow
  zlow: flow
  zhigh: flow
catalyst:
  script: /path
  implementation: paraview
  implementation_directory: /path
