---
problem: sod
eos: spiner
spiner_file: air.sp5
spiner_matid: 5030
kappa: 1.0e-100
mean_molecular_weight: 28.96
t0: 0.0
tf: 1.0
max_steps: 100
cfl: 0.3
max_dt: 1.0
log_frequency: 1
output_frequency: 1
levels: [5, 3, 3]
lowest_level: 5
coords:
  - [0.0, 0.0, 0.0]
  - [1.0, 1.0, 1.0]
boundaries:
  xlow: reflecting
  xhigh: reflecting
  ylow: flow
  yhigh: flow
  zlow: flow
  zhigh: flow
catalyst:
  script: /path
  implementation: paraview
  implementation_directory: /path
