config = {
    "problem": "acoustic-wave",
    "gamma": 1.4,
    "kappa": 1.0,
    "mean_molecular_weight": 1.0,
    "problem_parameters": {
        "scale": [3, 2, 1],
        "amplitude": 1e-5,
        "r0": 1.0,
        "p0": 1.0,
    },
    "eos": "ideal",
    "t0": 0.0,
    "tf": 1.0,
    "max_steps": 400,
    "cfl": 0.5,
    "max_dt": 1.0,
    "log_frequency": 100,
    "output_frequency": 100,
    "levels": [7, 6, 5],
    "coords": [[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]],
    "boundaries": {
        "xlow": "periodic",
        "xhigh": "periodic",
        "ylow": "periodic",
        "yhigh": "periodic",
        "zlow": "periodic",
        "zhigh": "periodic",
    },
    "output_method": "csv",
}
