config = {
    "problem": "acoustic-wave",
    "gamma": 1.4,
    "kappa": 1.0,
    "mean_molecular_weight": 1.0,
    "problem_parameters": {
        "scale": [5, 1, 1],
        "amplitude": 1e-7,
        "r0": 1.0,
        "p0": 1.0,
        "convergence_order": 2,
    },
    "eos": "ideal",
    "t0": 0.0,
    "tf": 1e-2,
    "max_steps": 500,
    "cfl": 0.1,
    "max_dt": 1.0,
    "log_frequency": 500,
    "output_frequency": 500,
    "levels": [12, 1, 1],
    "lowest_level": 12,
    "coords": [
        [0.0, 0.0, 0.0],
        [1.0, 1.0, 1.0],
    ],
    "boundaries": {
        "xlow": "periodic",
        "xhigh": "periodic",
        "ylow": "flow",
        "yhigh": "flow",
        "zlow": "flow",
        "zhigh": "flow",
    },
    "output_method": "csv",
}
